// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoomMates.Data;

#nullable disable

namespace Room_match_Lab.Migrations
{
    [DbContext(typeof(RoomMatesDbContext))]
    partial class RoomMatesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoomMates.Models.BookingRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("HousingId")
                        .HasColumnType("uuid");

                    b.Property<double>("MatchScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("double precision");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("HousingId");

                    b.HasIndex("ProfileId");

                    b.ToTable("BookingRequests");
                });

            modelBuilder.Entity("RoomMates.Models.Housing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowsSmoking")
                        .HasColumnType("boolean");

                    b.Property<string>("ApartmentNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BuildingNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("District")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("HasExistingPets")
                        .HasColumnType("boolean");

                    b.Property<double>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("PetPolicy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PricePerMonth")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("RequiredCleanliness")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredPartyTolerance")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredSleepSchedule")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Housings", t =>
                        {
                            t.HasCheckConstraint("CK_Housings_RequiredCleanliness", "\"RequiredCleanliness\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Housings_RequiredPartyTolerance", "\"RequiredPartyTolerance\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Housings_RequiredSleepSchedule", "\"RequiredSleepSchedule\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("RoomMates.Models.HousingCriterionRequirement", b =>
                {
                    b.Property<Guid>("HousingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LifestyleCriterionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.HasKey("HousingId", "LifestyleCriterionId");

                    b.HasIndex("LifestyleCriterionId");

                    b.ToTable("HousingCriterionRequirement");
                });

            modelBuilder.Entity("RoomMates.Models.HousingTag", b =>
                {
                    b.Property<Guid>("HousingId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("HousingId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("HousingTag");
                });

            modelBuilder.Entity("RoomMates.Models.LifestyleCriterion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("ScaleMax")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<int>("ScaleMin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("LifestyleCriteria", t =>
                        {
                            t.HasCheckConstraint("CK_LifestyleCriteria_Scale", "\"ScaleMin\" < \"ScaleMax\"");
                        });
                });

            modelBuilder.Entity("RoomMates.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("Budget")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<int>("Cleanliness")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("boolean");

                    b.Property<bool>("OwnPets")
                        .HasColumnType("boolean");

                    b.Property<int>("PartyTolerance")
                        .HasColumnType("integer");

                    b.Property<string>("PetTolerance")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SleepSchedule")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Profiles", t =>
                        {
                            t.HasCheckConstraint("CK_Profiles_Cleanliness", "\"Cleanliness\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Profiles_PartyTolerance", "\"PartyTolerance\" BETWEEN 1 AND 5");

                            t.HasCheckConstraint("CK_Profiles_SleepSchedule", "\"SleepSchedule\" BETWEEN 1 AND 5");
                        });
                });

            modelBuilder.Entity("RoomMates.Models.ProfileCriterionValue", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LifestyleCriterionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("ProfileId", "LifestyleCriterionId");

                    b.HasIndex("LifestyleCriterionId");

                    b.ToTable("ProfileCriterionValue");
                });

            modelBuilder.Entity("RoomMates.Models.ProfileTag", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("ProfileId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ProfileTag");
                });

            modelBuilder.Entity("RoomMates.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("RoomMates.Models.BookingRequest", b =>
                {
                    b.HasOne("RoomMates.Models.Housing", "Housing")
                        .WithMany("BookingRequests")
                        .HasForeignKey("HousingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomMates.Models.Profile", "Profile")
                        .WithMany("BookingRequests")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Housing");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RoomMates.Models.HousingCriterionRequirement", b =>
                {
                    b.HasOne("RoomMates.Models.Housing", "Housing")
                        .WithMany("CustomRequirements")
                        .HasForeignKey("HousingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomMates.Models.LifestyleCriterion", "LifestyleCriterion")
                        .WithMany("HousingRequirements")
                        .HasForeignKey("LifestyleCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Housing");

                    b.Navigation("LifestyleCriterion");
                });

            modelBuilder.Entity("RoomMates.Models.HousingTag", b =>
                {
                    b.HasOne("RoomMates.Models.Housing", "Housing")
                        .WithMany("HousingTags")
                        .HasForeignKey("HousingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomMates.Models.Tag", "Tag")
                        .WithMany("HousingTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Housing");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RoomMates.Models.ProfileCriterionValue", b =>
                {
                    b.HasOne("RoomMates.Models.LifestyleCriterion", "LifestyleCriterion")
                        .WithMany("ProfileValues")
                        .HasForeignKey("LifestyleCriterionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomMates.Models.Profile", "Profile")
                        .WithMany("CustomCriterionValues")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LifestyleCriterion");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("RoomMates.Models.ProfileTag", b =>
                {
                    b.HasOne("RoomMates.Models.Profile", "Profile")
                        .WithMany("ProfileTags")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoomMates.Models.Tag", "Tag")
                        .WithMany("ProfileTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("RoomMates.Models.Housing", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("CustomRequirements");

                    b.Navigation("HousingTags");
                });

            modelBuilder.Entity("RoomMates.Models.LifestyleCriterion", b =>
                {
                    b.Navigation("HousingRequirements");

                    b.Navigation("ProfileValues");
                });

            modelBuilder.Entity("RoomMates.Models.Profile", b =>
                {
                    b.Navigation("BookingRequests");

                    b.Navigation("CustomCriterionValues");

                    b.Navigation("ProfileTags");
                });

            modelBuilder.Entity("RoomMates.Models.Tag", b =>
                {
                    b.Navigation("HousingTags");

                    b.Navigation("ProfileTags");
                });
#pragma warning restore 612, 618
        }
    }
}
